export const PROVINCES = [
  "Aceh",
  "Bali",
  "Banten",
  "Bengkulu",
  "DI Yogyakarta",
  "DKI Jakarta",
  "Gorontalo",
  "Jambi",
  "Jawa Barat",
  "Jawa Tengah",
  "Jawa Timur",
  "Kalimantan Barat",
  "Kalimantan Selatan",
  "Kalimantan Tengah",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Kepulauan Bangka Belitung",
  "Kepulauan Riau",
  "Lampung",
  "Maluku",
  "Maluku Utara",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Papua",
  "Papua Barat",
  "Papua Barat Daya",
  "Papua Pegunungan",
  "Papua Selatan",
  "Papua Tengah",
  "Riau",
  "Sulawesi Barat",
  "Sulawesi Selatan",
  "Sulawesi Tengah",
  "Sulawesi Tenggara",
  "Sulawesi Utara",
  "Sumatera Barat",
  "Sumatera Selatan",
  "Sumatera Utara",
] as const;

// Alternative export for backward compatibility
export const INDONESIAN_PROVINCES = PROVINCES;

export type Province = (typeof PROVINCES)[number];

export const CITIES_BY_PROVINCE: Record<string, string[]> = {
  "DKI Jakarta": [
    "Jakarta Pusat",
    "Jakarta Utara",
    "Jakarta Barat",
    "Jakarta Selatan",
    "Jakarta Timur",
    "Kepulauan Seribu",
  ],
  "Jawa Barat": [
    "Bandung",
    "Bekasi",
    "Bogor",
    "Cirebon",
    "Depok",
    "Sukabumi",
    "Tasikmalaya",
    "Banjar",
    "Cimahi",
    "Bandung (Kab)",
    "Bekasi (Kab)",
    "Bogor (Kab)",
    "Ciamis",
    "Cianjur",
    "Cirebon (Kab)",
    "Garut",
    "Indramayu",
    "Karawang",
    "Kuningan",
    "Majalengka",
    "Pangandaran",
    "Purwakarta",
    "Subang",
    "Sukabumi (Kab)",
    "Sumedang",
    "Tasikmalaya (Kab)",
  ],
  "Jawa Tengah": [
    "Semarang",
    "Surakarta",
    "Magelang",
    "Pekalongan",
    "Salatiga",
    "Tegal",
    "Banyumas",
    "Batang",
    "Blora",
    "Boyolali",
    "Brebes",
    "Cilacap",
    "Demak",
    "Grobogan",
    "Jepara",
    "Karanganyar",
    "Kebumen",
    "Kendal",
    "Klaten",
    "Kudus",
    "Magelang (Kab)",
    "Pati",
    "Pekalongan (Kab)",
    "Pemalang",
    "Purbalingga",
    "Purworejo",
    "Rembang",
    "Semarang (Kab)",
    "Sragen",
    "Sukoharjo",
    "Tegal (Kab)",
    "Temanggung",
    "Wonogiri",
    "Wonosobo",
  ],
  "Jawa Timur": [
    "Surabaya",
    "Malang",
    "Kediri",
    "Blitar",
    "Madiun",
    "Mojokerto",
    "Pasuruan",
    "Probolinggo",
    "Banyuwangi",
    "Bangkalan",
    "Bojonegoro",
    "Bondowoso",
    "Gresik",
    "Jember",
    "Jombang",
    "Lamongan",
    "Lumajang",
    "Magetan",
    "Nganjuk",
    "Ngawi",
    "Pacitan",
    "Pamekasan",
    "Ponorogo",
    "Sampang",
    "Sidoarjo",
    "Situbondo",
    "Sumenep",
    "Trenggalek",
    "Tuban",
    "Tulungagung",
  ],
  "DI Yogyakarta": [
    "Yogyakarta",
    "Bantul",
    "Gunungkidul",
    "Kulon Progo",
    "Sleman",
  ],
  Banten: [
    "Serang",
    "Tangerang",
    "Tangerang Selatan",
    "Cilegon",
    "Lebak",
    "Pandeglang",
    "Tangerang (Kab)",
  ],
};

export const EDUCATION_LEVELS = [
  "SMA/SMK",
  "D3",
  "S1",
  "S2",
  "S3",
  "Pesantren",
  "Lainnya",
] as const;

export type EducationLevel = (typeof EDUCATION_LEVELS)[number];

export const MARITAL_STATUS = ["Single", "Janda", "Duda"] as const;
// Alternative export name for backward compatibility
export const MARITAL_STATUSES = MARITAL_STATUS;

export type MaritalStatus = (typeof MARITAL_STATUS)[number];

export const INCOME_RANGES = [
  "0-2 juta",
  "2-5 juta",
  "5-10 juta",
  "10-20 juta",
  "> 20 juta",
  "Saat Taaruf",
] as const;

export type IncomeRange = (typeof INCOME_RANGES)[number];
