-- =====================================================
-- Migration: 02 - Create Core Tables
-- Description: profiles, provinces, sequences
-- Author: Roomah Development Team
-- Date: 2025-01-16
-- =====================================================

-- =====================================================
-- Table: provinces (Master Data)
-- =====================================================
CREATE TABLE public.provinces (
  id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE
);

COMMENT ON TABLE public.provinces IS 'Indonesia provinces master data from BPS (Badan Pusat Statistik)';
COMMENT ON COLUMN public.provinces.name IS 'Official province name';

-- =====================================================
-- Table: profiles (Extended User Data)
-- =====================================================
CREATE TABLE public.profiles (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  full_name text,
  gender public.gender_enum,
  dob date,
  province_id smallint REFERENCES public.provinces(id) ON DELETE SET NULL,
  education public.education_enum,
  occupation text,
  avatar_path text,
  is_admin boolean NOT NULL DEFAULT false,
  registered_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

COMMENT ON TABLE public.profiles IS 'Extended user profile data beyond Supabase Auth';
COMMENT ON COLUMN public.profiles.user_id IS 'FK to auth.users - CASCADE delete on account closure';
COMMENT ON COLUMN public.profiles.email IS 'Cached from auth.users for quick access';
COMMENT ON COLUMN public.profiles.registered_at IS 'Set after onboarding completion (5Q + optional CV)';
COMMENT ON COLUMN public.profiles.is_admin IS 'Superadmin flag - requires provider=email (Google OAuth blocked for admin)';
COMMENT ON COLUMN public.profiles.avatar_path IS 'Storage path to Supabase Storage bucket';

-- =====================================================
-- Table: onboarding_verifications (5Q Tracking)
-- =====================================================
CREATE TABLE public.onboarding_verifications (
  user_id uuid PRIMARY KEY REFERENCES public.profiles(user_id) ON DELETE CASCADE,
  q1 boolean NOT NULL,
  q2 boolean NOT NULL,
  q3 boolean NOT NULL,
  q4 boolean NOT NULL,
  q5 boolean NOT NULL,
  committed boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

COMMENT ON TABLE public.onboarding_verifications IS 'Sensitive 5Q readiness verification data - strict RLS owner-only';
COMMENT ON COLUMN public.onboarding_verifications.q1 IS 'Question 1: Marriage readiness';
COMMENT ON COLUMN public.onboarding_verifications.q2 IS 'Question 2: Islamic knowledge';
COMMENT ON COLUMN public.onboarding_verifications.q3 IS 'Question 3: Family support';
COMMENT ON COLUMN public.onboarding_verifications.q4 IS 'Question 4: Financial readiness';
COMMENT ON COLUMN public.onboarding_verifications.q5 IS 'Question 5: Mental readiness';
COMMENT ON COLUMN public.onboarding_verifications.committed IS 'User commitment to continue despite negative answers';

-- =====================================================
-- Table: sequences (Centralized Code Generation)
-- =====================================================
CREATE TABLE public.sequences (
  seq_key text PRIMARY KEY,
  last_number bigint NOT NULL DEFAULT 0,
  updated_at timestamptz DEFAULT now()
);

COMMENT ON TABLE public.sequences IS 'Centralized sequence counters for code generation with atomic increment';
COMMENT ON COLUMN public.sequences.seq_key IS 'Sequence identifier: CANDIDATE_IKHWAN, CANDIDATE_AKHWAT, TAARUF';
COMMENT ON COLUMN public.sequences.last_number IS 'Last generated sequence number';

-- Seed initial sequences
INSERT INTO public.sequences (seq_key, last_number) VALUES
  ('CANDIDATE_IKHWAN', 0),
  ('CANDIDATE_AKHWAT', 0),
  ('TAARUF', 0);
